replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/halogen-eon-470613-h3/dead-simpl-frontend/dead-simpl-frontend
  tag: main
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80